### ISSUE TITLE
Get sentence text in TSV output

### ISSUE THREAD

**Issue by hrshdhgd** [OntoGene/OGER#4]
Hello,

I am trying to output the sentence as a column in the output for the tagged concept. Is it just a parameter tweak or needs code addition?
So for

```
headers = ('DOCUMENT ID',
                   'TYPE',
                   'START POSITION',
                   'END POSITION',
                   'MATCHED TERM',
                   'PREFERRED FORM',
                   'ENTITY ID',
                   'ZONE',
                   'SENTENCE ID',
                   'ORIGIN',
                   'UMLS CUI')
```

I want to add a column ` 'SENTENCE' ` in the output
Thanks.

**Comment by lfurrer** [comment]
You mean the text of the entire sentence in one cell?
No, you can't achieve that with a parameter change.
Additional columns are only available for entity attributes.

There's the `text_tsv` format which includes the text of the entire sentence, but it's verticalised (similar to CoNLL, but the linearity may be disrupted by the entity annotations).

**Comment by hrshdhgd** [comment]
Yes, I mean the text of the entire sentence in one cell. Okay, so as per current design, it is not possible to get this , correct?

**Comment by lfurrer** [comment]
Not without patching the `TSVFormatter`.

You could add a line `sentence.text` here:
https://github.com/OntoGene/OGER/blob/f23cf9bec70ba51f85605f26f3de2df72f7c4d5a/oger/doc/tsv.py#L79-L90

You may have to escape tabs and newlines to be safe.

**Comment by hrshdhgd** [comment]
I was going through the code and that's exactly what I thought would satisfy the need. But`sentence.text` only contains a term in the sentence and not the sentence as a whole.

**Comment by lfurrer** [comment]
`sentence.text` is supposed to contain the entire sentence.
Could be a really short sentence, such as an entry in the MeSH listing of a PubMed abstract or an otherwise isolated word.

**Comment by lfurrer** [comment]
Closing this as stale.
