### ISSUE TITLE
PyPI release?

### ISSUE THREAD

**Issue by hrshdhgd** [OntoGene/OGER#6]
I was wondering if a PyPI release is in the horizon for OGER or no.

**Comment by cmungall** [comment]
It would be great for us if the OGER package was released in PyPI - let us know if you need help with this

**Comment by lfurrer** [comment]
Sorry for the silence.
It's not a big deal to push OGER to PyPI, so I'll have a look soon.
Though to be honest, I don't see too much added value, as package management systems like poetry or pip can install from a GitHub repo directly (and I fear this repo isn't going to receive a lot of updates in the future).

**Comment by lfurrer** [comment]
https://pypi.org/project/OGER/

**Comment by hrshdhgd** [comment]
Thank you @lfurrer !

**Comment by cmungall** [comment]
Thank you!!!
