### ISSUE TITLE
Load REST-API dictionary onto Local OGER

### ISSUE THREAD

**Issue by tanoramb** [OntoGene/OGER#7]
Hello,

Is it possible to load a dictionary provided by the REST-API onto the local version of OGER? If it is not possible, could you please provide such a dictionary to download?

Thank you

**Comment by lfurrer** [comment]
Maybe you're looking for something like the [Bio Term Hub][1]?

[1]: http://pub.cl.uzh.ch/purl/biodb/

**Comment by lfurrer** [comment]
Closing this as stale.
